name: ORG Strength
favicon: null
layout_spectrum: 0.6555727117229253
typography_spectrum: 0.06462150230072439
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#28a5db'
    - '#155672'
    - '#b8112f'
    - '#e9bac4'
  brandStrength: 0.2964925351552665
  lightness: 0.5210120684932917
  saturation: 0.9162466658744961
  rhythmicContrast: 0.5
purpose: []
